name: Build release binaries

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running the workflow"
        required: false
        default: "Manual execution"

env:
  CRATE_NAME: suiup
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  RUST_BACKTRACE: 1

jobs:
  test-matrix:
    name: ${{ matrix.platform.os-name }} with rust ${{ matrix.toolchain }}
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os-name: linux-x86_64
            runs-on: ubuntu-ghcloud
            target: x86_64-unknown-linux-musl
          - os-name: linux-aarch64
            runs-on: ubuntu-arm64
            target: aarch64-unknown-linux-musl
          - os-name: windows-aarch64
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc
          - os-name: windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
          - os-name: macos-x86_64
            runs-on: macos-latest
            target: x86_64-apple-darwin
          - os-name: macos-aarch64
            runs-on: macos-latest
            target: aarch64-apple-darwin
        toolchain:
          - stable
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: suiup
          target: ${{ matrix.platform.target }}
