name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running the workflow"
        required: false
        default: "Manual execution"

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ACTIONS_STEP_DEBUG: true

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt, clippy

      - name: Install cargo nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Add default bin directory to PATH (Windows only)
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "$USERPROFILE/AppData/Local/bin" >> $GITHUB_PATH
            git config --system core.longpaths true
          fi

      - name: Run tests with test
        shell: bash
        run: RUST_LOG=debug cargo nextest run --no-fail-fast --retries 4

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
